compatibility_date = "2024-03-21"
name = "medium-backend"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWVhOTZiZmQtN2I4NC00M2I0LWI4ZGUtNDBiN2IxMjYzYjgwIiwidGVuYW50X2lkIjoiNTllMGJmMDEyZjI5MmVhYjBhYmQzZTg3NWEyNmNiZThiYmE4ZGUyNGRhNmIxODE2Y2FjYTAzNmJiYTJjZDc0ZCIsImludGVybmFsX3NlY3JldCI6ImUwYjA0NDNlLTEwZWYtNGNkYS04NDhkLTEwNzkxYmIxZjM2NSJ9.dAhMBVgZzByVM9ajwGTv3w_SQkQry69-JRXEdD10j1Q"
JWT_SECRET="lajdfo232dfd"
